# Game
N_ANTS = 100
N_FOOD_SPOTS = 5
N_FOOD_PER_SPOT = 100

# Ant
ANT_SPEED = 40
ANT_VISION = 20

# Pygame
SCREEN_HEIGHT, SCREEN_WIDTH = 500, 500

# Chunks
CHUNK_WIDTH = 20
CHUNK_HEIGHT = 20
CHUNKS = (SCREEN_HEIGHT // CHUNK_WIDTH, SCREEN_WIDTH // CHUNK_HEIGHT)
